# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MusicTheorySite.com - Quick Tutorials &amp; Tips on Music Theory, Constructing Chord Progressions, and Improvisation. | Music Theory Site
author: Garrett Grimm
email: garret@grimmdude.com
description:  MusicTheorySite.com is your online resource for learning the basics of music theory from reading notes on a staff to constructing chord progressions for songwriters.  We also provide free online tools for determining the key of a song and help identifying chords on the guitar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://musictheorysite.com" # the base hostname & protocol for your site, e.g. http://example.com
analytics_account: UA-1454657-16

# Build settings
permalink: pretty
markdown: kramdown
theme: minima
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower_components
